---
when:
  branch: main
  event: [ push, pull_request]

steps:
  build:
    image: nixos/nix:2.24.0
    commands:
    - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
    - nix build
    - mkdir public
    - cp -ar result/. public/

  deploy:
    image: alpine/git:v2.45.2
    secrets:
      - codeberg_token
      - bot_email
    commands:
      - WORKDIR=`mktemp -d`
      - cp .domains $WORKDIR || true
      - cp -ar public/. $WORKDIR/
      - cd $WORKDIR
      - git init
      - git config user.name "JesusMtnez-bot"
      - git config user.email "$BOT_EMAIL"
      - git checkout --orphan pages
      - git add --all .
      - git commit --message "deploy resume"
      - git push --force https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO pages
    when:
      - event: push
        branch: main
