---
name: update-flakes

on:
  workflow_dispatch: # allows manual triggering

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1

      - name: install Nix
        uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.NIX_FLAKES_UPDATE_TOKEN }}
          pr-title: "chore(flake): update flake.lock"
          commit-msg: "chore(flake): update flake.lock"
          branch: "update_flake"
          git-author-name: "JesusMtnez[bot]"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-name: "JesusMtnez[bot]"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
